### ISSUE TITLE
Timing of FunctionCalling Callbacks

### ISSUE THREAD

**Issue by ghost** [SciML/DiffEqCallbacks.jl#101]
`cb = FunctionCallingCallback(my_func!;
                                       funcat=[timesteps],
                                       func_everystep=false,
                                       func_start=false,
                                       tdir=1)
`
`sol = solve(prob,SSPRK104(),dt=dt,callback=cb,tstops=[timesteps])`
 
Im currently using this solver configuration with tstops representing when I need a model to stop and resolve a callback function. I've noticed that the callbacks resolve at all timesteps before the actual solve. Though the timesteps passed through to the callback is correct, the order is not guaranteed. 

Just confirming, is this a known feature for callbacks, or is there a way to guarantee callbacks are called only at the exact timesteps requested. 

Cheers,

**Comment by ChrisRackauckas** [comment]
If you want the behavior of a PresetTimeCallback, then use that. That seems more akin to what you're trying to do here. Or set the condition however you want. This is literally not the point of the FunctionCallingCallback, which is to emulate the saving behavior and step over the time points and call at every step something that would interpolate back at the appropriate times. It's not a feature of all callbacks, that's a documented feature of this specific one, and its specific purpose.
