### ISSUE TITLE
reexport? `ERROR: UndefVarError: `CallbackSet` not defined`

### ISSUE THREAD

**Issue by anandijain** [SciML/DiffEqCallbacks.jl#135]
I have a library that builds the (args, kws) of the `ODEProblem` call, and only really needs DiffEqCallbacks, so I only have `using DiffEqCallbacks` 

it was weird when my function errored due to `ERROR: UndefVarError: `CallbackSet` not defined`. 
I would expect it to live here, but it actually lives in SciMLBase.

**Comment by ChrisRackauckas** [comment]
It should maybe reexport SciMLBase like the solvers do? I don't know though: you don't need the solvers for this library.
