### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqCallbacks.jl#139]
https://docs.sciml.ai/DiffEqCallbacks/dev/projection/#Manifold-Projection

nlsolve: A nonlinear solver as defined [in the nlsolve format](https://docs.sciml.ai/DiffEqCallbacks/dev/projection/linear_nonlinear.html)

**Comment by ChrisRackauckas** [comment]
We really just need to do an update that makes that a NonlinearSolve.jl solver.
