### ISSUE TITLE
Missing performance optimization in the IntegratingCallback

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqCallbacks.jl#152]
As mentioned in https://github.com/SciML/DiffEqCallbacks.jl/pull/151/files#r1240881107

> One performance optimization: if isinplace(integrator.sol.prob), then we may want to have a cache vector and do integrator(cache,t_temp) in-place into the cache, and then @. integral += gauss_weights[n][i]*affect!.integrand_func(cache, t_temp, integrator). But also, we may want to allow for the integrand_func itself to be integrand_func!(obs,u,t,integrator) that writes into obs and make this:

```julia
if inplace(integrator.sol.prob)
  integrator(cache,t_temp)`
  affect!.integrand_func(obs, t_temp, integrator)
  @. integral += gauss_weights[n][i]*obs
else
  integral .+= gauss_weights[n][i]*affect!.integrand_func(integrator(t_temp), t_temp, integrator)
end
```

>That way it can be fully non-allocating.

**Comment by acoh64** [comment]
Opened PR here: https://github.com/SciML/DiffEqCallbacks.jl/pull/154
