### ISSUE TITLE
Periodic callback default behaviour

### ISSUE THREAD

**Issue by jgreener64** [SciML/DiffEqCallbacks.jl#97]
It is stated in the readme and the docs that the default value of `initial_affect` for `PeriodicCallback` is `true`. In fact it is `false`: https://github.com/SciML/DiffEqCallbacks.jl/blob/ea4768444af84e123ab142e3b705ba79b8949bd9/src/iterative_and_periodic.jl#L60

Happy to make a PR to fix this but I don't know which it is intended to be.

**Comment by ChrisRackauckas** [comment]
it should be false.
